server:
  port: 9001

spring:
  application:
    name: Worker Service

  datasource:
    url: jdbc:mysql://localhost:3306/workers?serverTimezone=UTC
    username: root
    password: 12345

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    doc-expansion: none

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
